services:
  playa:
    build:
      context: ..
      dockerfile: docker/Dockerfile.playa
    volumes:
      - ../config/playa:/config
    ports:
      - "9854:9854"
    environment:
      - CONFIG_PATH=/config/local.yaml
    restart: unless-stopped

  proxystorage:
    build:
      context: ..
      dockerfile: docker/Dockerfile.proxystorage
    volumes:
      - ../config/proxystorage:/config
    ports:
      - "9855:9855"
    environment:
      - CONFIG_PATH=/config/proxystorage-local.yaml
    restart: unless-stopped